import { combineReducers } from "redux";

const isLoading = (state = false, { type }) => {
  // for all dispatches generated by API generally
  if (/^.+_PENDING$/gi.test(type)) {
    return true;
  }

  if (/^.+_(SUCCESS|FAIL(URE|ED)?)$/gi.test(type)) {
    return false;
  }

  switch (type) {
    case "@@reactReduxFirebase/LOGIN":
    case "@@reactReduxFirebase/LOGIN_ERROR":
    case "@@reactReduxFirebase/AUTH_EMPTY_CHANGE":
      return false;
    case "@@reactReduxFirebase/AUTHENTICATION_INIT_STARTED":
      return true;
    default:
      return state;
  }
};

export default combineReducers({
  isLoading,
});
